let eventos = []

//Agrego conciertos
eventos.push(new Concierto("3 personas para ir a ver a Ciro","Movistar Arena","08-08-2024","20:00","4","Ciro y los Persas","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Maria Becerra con 3 chicas","Monumental - River","10-10-2024","19:00","4","María Becerra","Reguetón","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Babasónicos","Plaza de la música- Córdoba","08-11-2024","20:30","3","Babasónicos","Pop Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Las Pastillas del Abuelo","Villa Ballester","13-07-2024","18:00","4","Pastillas del Abuelo","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Eric Clapton","Estadio José Amalfitani- cancha Vélez","20-09-2024","18:00","3","Eric Clapton","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver Iron Maiden","Estadio Tomás Adolfo Ducó- cancha Huracán","01-12-2024","19:00","4","Iron Maiden","Metal","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Coldplay","Estadio Nacional","25-07-2024","20:00","4","Coldplay","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Disfrutar de Shakira","Arena Monterrey","30-08-2024","21:00","4","Shakira","Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Bruno Mars","Estadio Azteca","15-09-2024","19:00","4","Bruno Mars","Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ir a ver a Adele","O2 Arena","10-10-2024","20:00","4","Adele","Soul","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Asistir al concierto de Beyonce","Madison Square Garden","22-11-2024","21:00","4","Beyonce","R&B","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Concierto de Taylor Swift","Wembley Stadium","05-12-2024","20:00","4","Taylor Swift","Country Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Escuchar a The Weeknd","Staples Center","12-07-2024","19:00","4","The Weeknd","R&B","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Lady Gaga","MGM Grand Garden Arena","18-08-2024","21:00","4","Lady Gaga","Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ir al concierto de Ed Sheeran","ANZ Stadium","29-09-2024","20:00","4","Ed Sheeran","Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Concierto de Metallica","Olympic Stadium","14-10-2024","19:00","4","Metallica","Metal","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Justin Bieber","Rod Laver Arena","07-11-2024","21:00","4","Justin Bieber","Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Disfrutar de Dua Lipa","Ziggo Dome","25-12-2024","20:00","4","Dua Lipa","Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Asistir al concierto de Ariana Grande","AccorHotels Arena","15-07-2024","19:00","4","Ariana Grande","Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Drake en vivo","Scotiabank Arena","20-08-2024","21:00","4","Drake","Hip-Hop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ir al concierto de Billie Eilish","SAP Center","11-09-2024","20:00","4","Billie Eilish","Alternative","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Disfrutar de The Rolling Stones","Gillette Stadium","03-10-2024","19:00","4","The Rolling Stones","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Elton John","Barclays Center","22-11-2024","20:00","4","Elton John","Pop Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Asistir al concierto de U2","MetLife Stadium","05-12-2024","21:00","4","U2","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ir a ver a Queen","O2 Arena","15-07-2024","19:00","4","Queen","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Concierto de Green Day","Petco Park","30-08-2024","21:00","4","Green Day","Punk Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Foo Fighters","Fenway Park","10-09-2024","20:00","4","Foo Fighters","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Disfrutar de Imagine Dragons","Allegiant Stadium","25-10-2024","19:00","4","Imagine Dragons","Pop Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Asistir al concierto de The Beatles","Twickenham Stadium","18-11-2024","20:00","4","The Beatles","Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ir a ver a Muse","Stade de France","07-12-2024","21:00","4","Muse","Alternative Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Disfrutar de Maroon 5","Mercedes-Benz Stadium","13-07-2024","20:00","4","Maroon 5","Pop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Pearl Jam","Dodger Stadium","29-08-2024","19:00","4","Pearl Jam","Grunge","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Asistir al concierto de Red Hot Chili Peppers","San Siro Stadium","09-09-2024","21:00","4","Red Hot Chili Peppers","Funk Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ir a ver a Linkin Park","Emirates Stadium","23-10-2024","20:00","4","Linkin Park","Nu Metal","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Concierto de Arctic Monkeys","Stade Vélodrome","05-11-2024","19:00","4","Arctic Monkeys","Indie Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ver a Kings of Leon","Olympiastadion","18-12-2024","21:00","4","Kings of Leon","Alternative Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Disfrutar de Panic! at the Disco","Allianz Arena","12-07-2024","20:00","4","Panic! at the Disco","Pop Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Asistir al concierto de Imagine Dragons","Estadio Monumental","30-08-2024","21:00","4","Imagine Dragons","Pop Rock","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Concierto("Ir al concierto de Twenty One Pilots","Amsterdam Arena","15-09-2024","20:00","4","Twenty One Pilots","Alternative Hip-Hop","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));

//Agrego deportes
eventos.push(new Deporte("3 personas para el padel","Complejo deportivo Gonnet","14-07-2024","20:00","4","Deportivo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("9 para jugar al futbol","Cancha Predio Norte","21-07-2024","21:00","10","Deportivo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("3 para tenis","Predio Agua Potable","13-07-2024","10:00","4","Deportivo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("4 para turno de hockey","Predio club universitario","16-07-2024","16:00","5","Deportivo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("1 para ajedrez","Plaza San Martín","11-07-2024","12:00","2","Deportivo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("3 para correr","El Rosedal de Palermo","15-07-2024","19:00","4","Deportivo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Partido de voleibol","Gimnasio Municipal","17-07-2024","17:00","12","Voleibol","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Torneo de baloncesto","Cancha Central","18-07-2024","18:00","10","Baloncesto","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Carrera de 5K","Parque del Sol","19-07-2024","08:00","50","Carrera","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Sesión de yoga al aire libre","Playa Norte","20-07-2024","07:00","20","Yoga","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de Zumba","Centro Cultural","21-07-2024","18:30","30","Zumba","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Torneo de tenis","Club de Tenis","22-07-2024","10:00","16","Tenis","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de natación","Piscina Olímpica","23-07-2024","09:00","10","Natación","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Partido de rugby","Campo Deportivo","24-07-2024","16:00","30","Rugby","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Entrenamiento de boxeo","Gimnasio Golden Gloves","25-07-2024","18:00","6","Boxeo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Competencia de ciclismo","Ruta 66","26-07-2024","07:00","100","Ciclismo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de pilates","Estudio Zen","27-07-2024","11:00","12","Pilates","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Entrenamiento de crossfit","Parque Central","28-07-2024","06:00","15","Crossfit","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de escalada","Muro de Escalada","29-07-2024","14:00","8","Escalada","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Torneo de golf","Club de Golf","30-07-2024","08:00","4","Golf","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Partido de balonmano","Polideportivo Municipal","31-07-2024","12:00","14","Balonmano","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de kickboxing","Gimnasio Fight Club","01-08-2024","18:00","10","Kickboxing","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Sesión de meditación guiada","Jardín Botánico","02-08-2024","07:30","20","Meditación","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Entrenamiento de fútbol americano","Estadio Nacional","03-08-2024","16:00","22","Fútbol Americano","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de danza contemporánea","Estudio de Danza","04-08-2024","17:00","10","Danza","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Competencia de remo","Lago Azul","05-08-2024","06:00","30","Remo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Torneo de ajedrez","Café Literario","06-08-2024","15:00","20","Ajedrez","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Partido de cricket","Campo de Cricket","07-08-2024","11:00","22","Cricket","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de judo","Dojo Kenshi","08-08-2024","18:30","12","Judo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Entrenamiento de lucha libre","Centro Deportivo","09-08-2024","19:00","8","Lucha Libre","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de artes marciales mixtas","Gimnasio MMA","10-08-2024","20:00","10","Artes Marciales Mixtas","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Competencia de tiro con arco","Campo de Tiro","11-08-2024","09:00","15","Tiro con Arco","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de Tai Chi","Parque de la Paz","12-08-2024","07:00","15","Tai Chi","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Partido de squash","Club de Squash","13-08-2024","16:00","4","Squash","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Sesión de stretching","Gimnasio Fit","14-08-2024","08:00","12","Stretching","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Clase de defensa personal","Gimnasio Defensa","15-08-2024","19:00","8","Defensa Personal","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Deporte("Torneo de esgrima","Polideportivo Municipal","16-08-2024","10:00","20","Esgrima","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));



//Agrego domingueando
eventos.push(new Domingueando("3 personas para tomar mates","Plaza Moreno","14-07-2024","15:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("5 para ir a cenar a un tenedor libre","Parrilla El Retiro","14-07-2024","21:00","5","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("2 para ir a pescar","Laguna la Salada","21-07-2024","06:00","3","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("1 para ir al cine a ver Intensamente 2","Cinema Rocha","14-07-2024","18:00","2","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("3 para hacer club de lectura","Café La Callecita","28-07-2024","16:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("4 para ver final de Copa América","Antares Cervecería","14-07-2024","20:30","5","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Tomar mate en el parque","Parque Rivadavia","17-07-2024","16:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Cena en restaurante italiano","Trattoria Napoli","18-07-2024","20:00","5","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Pesca en el río","Río Paraná","19-07-2024","06:00","3","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Club de lectura en la biblioteca","Biblioteca Nacional","20-07-2024","14:00","8","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver película en cine independiente","Cine Arteplex","21-07-2024","18:00","2","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver partido de fútbol","Estadio Monumental","22-07-2024","19:00","10","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Tomar mate en la plaza","Plaza Francia","23-07-2024","15:00","6","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Cena en parrilla","Parrilla Los Amigos","24-07-2024","21:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Pesca en el lago","Lago del Bosque","25-07-2024","07:00","5","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Lectura en el café","Café Literario","26-07-2024","17:00","3","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver documental en el centro cultural","Centro Cultural Recoleta","27-07-2024","19:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver final de torneo de tenis","Club de Tenis","28-07-2024","16:00","8","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Tomar mate en el jardín botánico","Jardín Botánico","29-07-2024","14:00","5","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Cena en restaurante de sushi","Sushi Club","30-07-2024","20:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Pesca en la laguna","Laguna de Chascomús","31-07-2024","05:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Lectura en el parque","Parque Centenario","01-08-2024","11:00","6","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver película en cine al aire libre","Parque de la Costa","02-08-2024","20:30","3","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver partido de básquet","Estadio Obras","03-08-2024","18:00","7","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Tomar mate en la playa","Playa Grande","04-08-2024","10:00","6","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Cena en restaurante mexicano","La Cantina","05-08-2024","21:00","5","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Pesca en el arroyo","Arroyo Saladillo","06-08-2024","06:00","3","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Lectura en la terraza","Terraza del Centro Cultural","07-08-2024","16:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver musical en teatro","Teatro Gran Rex","08-08-2024","20:00","6","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver partido de tenis","Estadio Parque Roca","09-08-2024","15:00","8","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Tomar mate en el campo","Estancia La Esperanza","10-08-2024","09:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Cena en restaurante vegetariano","Green Eats","11-08-2024","20:00","4","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Pesca en el embalse","Embalse Río Tercero","12-08-2024","07:00","3","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Lectura en el museo","Museo de Arte Moderno","13-08-2024","13:00","2","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver función de circo","Circo Rodas","14-08-2024","19:00","5","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));
eventos.push(new Domingueando("Ver partido de rugby","Estadio CASI","15-08-2024","17:00","10","Recreativo","https://chat.whatsapp.com/Gh2UhTbBNig0BrjrUJTCnj"));